# global
data_dir:
docker_network_name:
PUID:
PGID:
TZ:

# glance
GLANCE_PIHOLE_TOKEN:
GLANCE_VIDEO_MACHINE:
GLANCE_JELLYFIN_URL:
GLANCE_JELLYFIN_TOKEN:

# tinyauth
TINYAUTH_USERS:
TINYAUTH_SECRET:
TINYAUTH_APP_URL:
TINYAUTH_GENERIC_CLIENT_ID:
TINYAUTH_GENERIC_CLIENT_SECRET:
TINYAUTH_GENERIC_AUTH_URL:
TINYAUTH_GENERIC_TOKEN_URL:
TINYAUTH_GENERIC_USER_URL:
TINYAUTH_GENERIC_SCOPES:
TINYAUTH_GENERIC_NAME:
TINYAUTH_OAUTH_WHITELIST:
TINYAUTH_APP_TITLE:
TINYAUTH_BACKGROUND_IMAGE:

# code-server
CODE_PROXY_DOMAIN:
CODE_DEFAULT_WORKSPACE:

# dozzle
DOZZLE_ACTIONS:
DOZZLE_SHELL:

# gluetun
GLUETUN_VPN_SERVICE_PROVIDER:
GLUETUN_VPN_TYPE:
GLUETUN_WIREGUARD_PRIVATE_KEY:
GLUETUN_WIREGUARD_ADDRESSES:
GLUETUN_SERVER_COUNTRIES:
GLUETUN_SERVER_CITIES:
GLUETUN_SERVER_HOSTNAMES:

# immich
IMMICH_UPLOAD_LOCATION:
IMMICH_DB_DATA_LOCATION: /postgres
IMMICH_VERSION: release
IMMICH_DB_PASSWORD: postgres
IMMICH_DB_USERNAME: postgres
IMMICH_DB_DATABASE_NAME: postgres

# jellyfin
JELLYFIN_TV_PATH:
JELLYFIN_MOVIE_PATH:
JELLYFIN_MUSIC_PATH:

# navidrome
NAVIDROME_MUSIC_PATH:

# nextcloud
NEXTCLOUD_POSTGRES_PASSWORD:
NEXTCLOUD_POSTGRES_DATABASE:
NEXTCLOUD_POSTGRES_USER:
NEXTCLOUD_POSTGRES_HOST:

# ntfy
NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
NTFY_BASE_URL:

# nzbget
NZBGET_USER:
NZBGET_PASS:
NZBGET_DOWNLOADS_PATH:

# pihole
PIHOLE_FTLCONF_WEBSERVER_API_PASSWORD:

# pocketid
POCKETID_APP_URL:
POCKETID_TRUST_PROXY:

# romm
ROMM_AUTH_SECRET_KEY:
ROMM_LIBRARY_PATH:
ROMM_IGDB_CLIENT_ID:
ROMM_IGDB_CLIENT_SECRET:
ROMM_OIDC_ENABLED:
ROMM_OIDC_PROVIDER:
ROMM_OIDC_CLIENT_ID:
ROMM_OIDC_CLIENT_SECRET:
ROMM_OIDC_REDIRECT_URL:
ROMM_SERVER_APPLICATION_URL:

# servarr
SERVARR_MEDIA_PATH:

# syncthing
SYNCTHING_DATA_PATH:

# vaultwarden
VAULTWARDEN_DOMAIN:
