---
- name: Create folder structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_dir }}/calibre"

- name: Pull latest Calibre-Web Docker Image
  docker_image:
    name: lscr.io/linuxserver/calibre-web
    tag: latest
    source: pull

- name: Deploy Calibre-Web Docker Container
  docker_container:
    name: calibre
    image: lscr.io/linuxserver/calibre-web
    recreate: true
    restart_policy: unless-stopped
    volumes:
      - "{{ data_dir }}/calibre:/config"
      - "{{ media_path }}/Books/Novels:/books"
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ TZ }}"
      DOCKER_MODS: linuxserver/mods:universal-calibre
    networks:
      - name: homelab
    # labels:
    # traefik.enable: "true"
    # traefik.http.routers.read.rule: Host(`read.fntz.net`)
    # traefik.http.routers.read.entrypoints: webSecure
    # traefik.http.routers.read.tls.certresolver: letsencrypt
    # traefik.http.services.read.loadbalancer.server.port: "8083"
