---
- name: Deploy Code Server
  include_role:
    name: docker
  vars:
    name: "codeserver"
    directories:
      - "{{ data_dir }}/code-server"
    image:
      name: lscr.io/linuxserver/code-server
      tag: latest
    networks:
      - name: homelab
    volumes:
      - "{{ data_dir }}/code-server:/config"
      - "{{ data_dir }}:/config/workspace/docker"
    env:
      PROXY_DOMAIN: "{{ CODE_PROXY_DOMAIN }}"
      DEFAULT_WORKSPACE: "{{ CODE_DEFAULT_WORKSPACE }}"
      TZ: "{{ TZ }}"
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.code.rule: Host(`code.fntz.net`)
      traefik.http.routers.code.entrypoints: webSecure
      traefik.http.routers.code.tls.certresolver: letsencrypt
      traefik.http.services.code.loadbalancer.server.port: "8443"
      traefik.http.routers.code.middlewares: tinyauth
