---
- name: Deploy Dashdot
  include_role:
    name: docker
  vars:
    name: dashdot
    image:
      name: mauricenino/dashdot
      tag: latest
    networks:
      - name: homelab
    volumes:
      - "/:/mnt/host:ro"
    labels:
      traefik.enable: "true"
      traefik.http.routers.dash.rule: Host(`stats.fntz.net`)
      traefik.http.routers.dash.entrypoints: webSecure
      traefik.http.routers.dash.tls.certresolver: letsencrypt
      traefik.http.services.dash.loadbalancer.server.port: "3001"
