---
- name: Deploy Dozzle
  include_role:
    name: docker
  vars:
    name: dozzle
    networks:
      - name: homelab
    image:
      name: amir20/dozzle
      tag: latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      DOZZLE_ENABLE_ACTIONS: "{{ DOZZLE_ACTIONS }}"
      DOZZLE_ENABLE_SHELL: "{{ DOZZLE_SHELL }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.dz.rule: Host(`logs.fntz.net`)
      traefik.http.routers.dz.entrypoints: webSecure
      traefik.http.routers.dz.tls.certresolver: letsencrypt
      traefik.http.services.dz.loadbalancer.server.port: "8080"
      traefik.http.routers.dz.middlewares: tinyauth
