---
- name: Create Dozzle Docker Container
  docker_container:
    name: dozzle
    image: amir20/dozzle:latest
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: homelab
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      DOZZLE_ENABLE_ACTIONS: "{{ DOZZLE_ACTIONS }}"
      DOZZLE_ENABLE_SHELL: "{{ DOZZLE_SHELL }}"
