---
- name: Deploy Gitea
  include_role:
    name: docker
  vars:
    name: gitea
    directories:
      - "{{ data_dir }}/gitea"
    image:
      name: docker.gitea.com/gitea
      tag: latest
    networks:
      - name: "{{ docker_network_name }}"
    volumes:
      - "{{ data_dir }}/gitea:/data"
      - "/home/git/.ssh:/data/git/.ssh"
    published_ports:
      - "2222:22"
    env:
      USER_UID: "1000"
      USER_GID: "1000"
    labels:
      traefik.enable: "true"
      traefik.http.routers.git.rule: Host(`git.alexav.gg`)
      traefik.http.routers.git.entrypoints: webSecure
      traefik.http.routers.git.tls.certresolver: letsencrypt
      traefik.http.services.git.loadbalancer.server.port: "3000"
