---
- name: Create folder structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_dir }}/glance"
    - "{{ data_dir }}/glance/config"
    - "{{ data_dir }}/glance/assets"

- name: Pull latest Glance Docker Image
  docker_image:
    name: glanceapp/glance
    tag: latest
    source: pull

- name: Create Glance Docker Container
  docker_container:
    name: glance
    image: glanceapp/glance
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: homelab
    env:
      PIHOLE_TOKEN: "{{ GLANCE_PIHOLE_TOKEN }}"
      VIDEO_MACHINE: "{{ GLANCE_VIDEO_MACHINE }}"
      JELLYFIN_URL: "{{ GLANCE_JELLYFIN_URL }}"
      JELLYFIN_TOKEN: "{{ GLANCE_JELLYFIN_TOKEN }}"
    volumes:
      - "{{ data_dir }}/glance/config:/app/config"
      - "{{ data_dir }}/glance/assets:/app/assets"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      traefik.enable: "true"
      traefik.http.routers.glance.rule: Host(`fntz.net`)
      traefik.http.routers.glance.entrypoints: webSecure
      traefik.http.routers.glance.tls.certresolver: letsencrypt
      traefik.http.services.glance.loadbalancer.server.port: "8080"
