---
- name: Deploy Homebridge
  include_role:
    name: docker
  vars:
    name: homebridge
    image:
      name: homebridge/homebridge
      tag: latest
    network_mode: host
    volumes:
      - "{{ data_dir }}/homebridge:/homebridge"
    labels:
      traefik.enable: "true"
      traefik.http.routers.bridge.rule: Host(`bridge.fntz.net`)
      traefik.http.routers.bridge.entrypoints: webSecure
      traefik.http.routers.bridge.tls.certresolver: letsencrypt
      traefik.http.services.bridge.loadbalancer.server.url: "http://{{ TRAEFIK_HOST_IP }}:8581"
      traefik.http.routers.bridge.middlewares: tinyauth
