---
- name: Create Folder structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_dir }}/homebridge"

- name: Create Homebridge Docker Container
  docker_container:
    name: homebridge
    image: homebridge/homebridge:latest
    restart_policy: unless-stopped
    network_mode: host
    recreate: true
    volumes:
      - "{{ data_dir }}/homebridge:/homebridge"
    labels:
      traefik.enable: "true"
      traefik.http.routers.bridge.rule: Host(`bridge.fntz.net`)
      traefik.http.routers.bridge.entrypoints: webSecure
      traefik.http.routers.bridge.tls.certresolver: letsencrypt
      traefik.http.services.bridge.loadbalancer.server.url: "http://{{ TRAEFIK_HOST_IP }}:8581"
      traefik.http.routers.bridge.middlewares: tinyauth
