---
- name: Create folder structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_dir }}/jackett"

- name: Pull latest Jackett Docker Image
  docker_image:
    name: lscr.io/linuxserver/jackett
    tag: latest
    source: pull

- name: Deploy Jackett Docker Container
  docker_container:
    name: jackett
    image: lscr.io/linuxserver/jackett
    recreate: true
    restart_policy: unless-stopped
    network_mode: "container:gluetun"
    volumes:
      - "{{ data_dir }}/jackett:/config"
      - "{{ media_path}}/Downloads:/downloads"
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ TZ }}"
