---
- name: Create folder structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_dir }}/jellyfin"

- name: Pull latest Jellyfin Docker Image
  docker_image:
    name: lscr.io/linuxserver/jellyfin
    tag: latest
    source: pull

- name: Create Jellyfin Docker Container
  docker_container:
    name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: homelab
    published_ports:
      - 8096:8096
    volumes:
      - "{{ data_dir }}/jellyfin:/config"
      - "{{ JELLYFIN_TV_PATH }}:/data/tvshows"
      - "{{ JELLYFIN_MOVIE_PATH }}:/data/movies"
      - "{{ JELLYFIN_MUSIC_PATH }}:/data/music"
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ TZ }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.jf.rule: Host(`jf.fntz.net`)
      traefik.http.routers.jf.entrypoints: webSecure
      traefik.http.routers.jf.tls.certresolver: letsencrypt
      traefik.http.services.jf.loadbalancer.server.port: "8096"
