---
- name: Create folder structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_dir }}/kavita"

- name: Pull latest Kavita Docker Image
  docker_image:
    name: lscr.io/linuxserver/kavita
    tag: latest
    source: pull

- name: Deploy Kavita Docker Container
  docker_container:
    name: kavita
    image: lscr.io/linuxserver/kavita
    recreate: true
    restart_policy: unless-stopped
    volumes:
      - "{{ data_dir }}/kavita:/config"
      - "{{ media_path }}/Books:/books"
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ TZ }}"
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.read.rule: Host(`read.fntz.net`)
      traefik.http.routers.read.entrypoints: webSecure
      traefik.http.routers.read.tls.certresolver: letsencrypt
      traefik.http.services.read.loadbalancer.server.port: "5000"
