---
- name: Create folder structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_dir }}/navidrome"

- name: Pull latest Navidrome Docker Image
  docker_image:
    name: deluan/navidrome
    tag: latest
    source: pull

- name: Create Navidrome Docker Container
  docker_container:
    name: navidrome
    image: deluan/navidrome:latest
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: homelab
    volumes:
      - "{{ data_dir }}/navidrome:/data"
      - "{{ NAVIDROME_MUSIC_PATH }}:/music:ro"
    labels:
      traefik.enable: "true"
      traefik.http.routers.music.rule: Host(`music.fntz.net`)
      traefik.http.routers.music.entrypoints: webSecure
      traefik.http.routers.music.tls.certresolver: letsencrypt
      traefik.http.services.music.loadbalancer.server.port: "4533"
