---
- name: Deploy NZBGet
  include_role:
    name: docker
  vars:
    name: nzbget
    directories:
      - "{{ data_dir }}/nzbget"
    image:
      name: lscr.io/linuxserver/nzbget
      tag: latest
    networks:
      - name: homelab
    volumes:
      - "{{ data_dir }}/nzbget:/config"
      - "{{ NZBGET_DOWNLOADS_PATH }}:/downloads"
    env:
      NZBGET_USER: "{{ NZBGET_USER }}"
      NZBGET_PASS: "{{ NZBGET_PASS }}"
      TZ: "{{ TZ }}"
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.nzb.rule: Host(`nzb.fntz.net`)
      traefik.http.routers.nzb.entrypoints: webSecure
      traefik.http.routers.nzb.tls.certresolver: letsencrypt
      traefik.http.services.nzb.loadbalancer.server.port: "6789"
      traefik.http.routers.nzb.middlewares: tinyauth
