---
- name: Create Folder structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_dir }}/pocketid"

- name: Create PocketID Docker Container
  docker_container:
    name: pocketid
    image: ghcr.io/pocket-id/pocket-id:v1
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: homelab
    volumes:
      - "{{ data_dir }}/pocketid:/app/data"
    env:
      APP_URL: "{{ POCKETID_APP_URL }}"
      TRUST_PROXY: "{{ POCKETID_TRUST_PROXY }}"
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
