---
- name: Create Folder structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_dir }}/pocketid"

- name: Pull latest PocketID Docker Image
  docker_image:
    name: ghcr.io/pocket-id/pocket-id
    tag: v1
    source: pull

- name: Create PocketID Docker Container
  docker_container:
    name: pocketid
    image: ghcr.io/pocket-id/pocket-id:v1
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: homelab
    volumes:
      - "{{ data_dir }}/pocketid:/app/data"
    env:
      APP_URL: "{{ POCKETID_APP_URL }}"
      TRUST_PROXY: "{{ POCKETID_TRUST_PROXY }}"
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.oidc.rule: Host(`oidc.fntz.net`)
      traefik.http.routers.oidc.entrypoints: webSecure
      traefik.http.routers.oidc.tls.certresolver: letsencrypt
      traefik.http.services.oidc.loadbalancer.server.port: "1411"
