---
- name: Deploy PocketID
  include_role:
    name: docker
  vars:
    name: pocketid
    directories:
      - "{{ data_dir }}/pocketid"
    image:
      name: ghcr.io/pocket-id/pocket-id
      tag: v1
    networks:
      - name: homelab
    volumes:
      - "{{ data_dir }}/pocketid:/app/data"
    env:
      APP_URL: "{{ POCKETID_APP_URL }}"
      TRUST_PROXY: "{{ POCKETID_TRUST_PROXY }}"
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.oidc.rule: Host(`oidc.fntz.net`)
      traefik.http.routers.oidc.entrypoints: webSecure
      traefik.http.routers.oidc.tls.certresolver: letsencrypt
      traefik.http.services.oidc.loadbalancer.server.port: "1411"
