---
- name: Deploy Radarr
  include_role:
    name: docker
  vars:
    name: radarr
    directories:
      - "{{ data_dir }}/servarr"
      - "{{ data_dir }}/servarr/sonarr_config"
      - "{{ data_dir }}/servarr/radarr_config"
      - "{{ data_dir }}/servarr/lidarr_config"
    image:
      name: lscr.io/linuxserver/radarr
      tag: latest
    volumes:
      - "{{ data_dir }}/servarr/radarr_config:/config"
      - "{{ SERVARR_MEDIA_PATH }}:/media"
      - "{{ NZBGET_DOWNLOADS_PATH }}:/downloads"
    networks:
      - name: homelab
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ TZ }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.radarr.rule: Host(`radarr.fntz.net`)
      traefik.http.routers.radarr.entrypoints: webSecure
      traefik.http.routers.radarr.tls.certresolver: letsencrypt
      traefik.http.services.radarr.loadbalancer.server.port: "7878"

- name: Deploy Sonarr
  include_role:
    name: docker
  vars:
    name: sonarr
    image:
      name: lscr.io/linuxserver/sonarr
      tag: latest
    volumes:
      - "{{ data_dir }}/servarr/sonarr_config:/config"
      - "{{ SERVARR_MEDIA_PATH }}:/data"
      - "{{ NZBGET_DOWNLOADS_PATH }}:/downloads"
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ TZ }}"
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr.rule: Host(`sonarr.fntz.net`)
      traefik.http.routers.sonarr.entrypoints: webSecure
      traefik.http.routers.sonarr.tls.certresolver: letsencrypt
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"

- name: Deploy Lidarr
  include_role:
    name: docker
  vars:
    name: lidarr
    image:
      name: lscr.io/linuxserver/lidarr
      tag: latest
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ TZ }}"
    volumes:
      - "{{ data_dir }}/servarr/lidarr_config:/config"
      - "{{ SERVARR_MEDIA_PATH }}:/media"
      - "{{ NZBGET_DOWNLOADS_PATH }}:/downloads"
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.lidarr.rule: Host(`lidarr.fntz.net`)
      traefik.http.routers.lidarr.entrypoints: webSecure
      traefik.http.routers.lidarr.tls.certresolver: letsencrypt
      traefik.http.services.lidarr.loadbalancer.server.port: "8686"
