---
- name: Create folder structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_dir }}/servarr"
    - "{{ data_dir }}/servarr/sonarr_config"
    - "{{ data_dir }}/servarr/radarr_config"
    - "{{ data_dir }}/servarr/lidarr_config"

- name: Deploy Radarr Container
  docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart_policy: unless-stopped
    recreate: true
    volumes:
      - "{{ data_dir }}/servarr/radarr_config:/config"
      - "{{ SERVARR_MEDIA_PATH }}:/media"
      - "{{ NZBGET_DOWNLOADS_PATH }}:/downloads"
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.radarr.rule: Host(`radarr.fntz.net`)
      traefik.http.routers.radarr.entrypoints: webSecure
      traefik.http.routers.radarr.tls.certresolver: letsencrypt
      traefik.http.services.radarr.loadbalancer.server.port: "7878"

- name: Deploy Sonarr Container
  docker_container:
    name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart_policy: unless-stopped
    recreate: true
    volumes:
      - "{{ data_dir }}/servarr/sonarr_config:/config"
      - "{{ SERVARR_MEDIA_PATH }}:/data"
      - "{{ NZBGET_DOWNLOADS_PATH }}:/downloads"
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr.rule: Host(`sonarr.fntz.net`)
      traefik.http.routers.sonarr.entrypoints: webSecure
      traefik.http.routers.sonarr.tls.certresolver: letsencrypt
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"

- name: Deploy Lidarr Container
  docker_container:
    name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart_policy: unless-stopped
    recreate: true
    volumes:
      - "{{ data_dir }}/servarr/lidarr_config:/config"
      - "{{ SERVARR_MEDIA_PATH }}:/media"
      - "{{ NZBGET_DOWNLOADS_PATH }}:/downloads"
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.lidarr.rule: Host(`lidarr.fntz.net`)
      traefik.http.routers.lidarr.entrypoints: webSecure
      traefik.http.routers.lidarr.tls.certresolver: letsencrypt
      traefik.http.services.lidarr.loadbalancer.server.port: "8686"
