---
- name: Create folder structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_dir }}/tautulli"

- name: Create Tautulli Docker Container
  docker_container:
    name: tautulli
    image: ghcr.io/tautulli/tautulli
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: homelab
    volumes:
      - "{{ data_dir }}/tautulli:/config"
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ TZ }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.tt.rule: Host(`tt.fntz.net`)
      traefik.http.routers.tt.entrypoints: webSecure
      traefik.http.routers.tt.tls.certresolver: letsencrypt
      traefik.http.services.tt.loadbalancer.server.port: "8181"
