---
- name: Deploy Termix
  include_role:
    name: docker
  vars:
    name: termix
    directories:
      - "{{ data_dir }}/termix"
    image:
      name: ghcr.io/lukegus/termix
      tag: latest
    networks:
      - name: homelab
    volumes:
      - "{{ data_dir }}/termix:/app/data"
    env:
      PORT: "8080"
    labels:
      traefik.enable: "true"
      traefik.http.routers.termix.rule: Host(`ssh.fntz.net`)
      traefik.http.routers.termix.entrypoints: webSecure
      traefik.http.routers.termix.tls.certresolver: letsencrypt
      traefik.http.services.termix.loadbalancer.server.port: "8080"
