---
- name: Deploy Uptime Kuma
  include_role:
    name: docker
  vars:
    name: uptime-kuma
    directories:
      - "{{ data_dir }}/uptime-kuma"
    image:
      name: louislam/uptime-kuma
      tag: latest
    networks:
      - name: homelab
    volumes:
      - "{{ data_dir }}/uptime-kuma:/app/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      traefik.enable: "true"
      traefik.http.routers.status.rule: Host(`status.fntz.net`)
      traefik.http.routers.status.entrypoints: webSecure
      traefik.http.routers.status.tls.certresolver: letsencrypt
      traefik.http.services.status.loadbalancer.server.port: "3001"
