---
- name: Deploy Vaultwarden
  include_role:
    name: docker
  vars:
    name: vaultwarden
    image:
      name: vaultwarden/server
      tag: latest
    networks:
      - name: homelab
    volumes:
      - "{{ data_dir }}/vaultwarden:/data"
    env:
      DOMAIN: "{{ VAULTWARDEN_DOMAIN }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.vw.rule: Host(`vw.fntz.net`)
      traefik.http.routers.vw.entrypoints: webSecure
      traefik.http.routers.vw.tls.certresolver: letsencrypt
      traefik.http.services.vw.loadbalancer.server.port: "80"
