---
- name: Create folder structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ data_dir }}/vaultwarden"

- name: Pull latest Vaultwarden Docker Image
  docker_image:
    name: vaultwarden/server
    tag: latest
    source: pull

- name: Create Vaultwarden Docker Container
  docker_container:
    name: vaultwarden
    image: vaultwarden/server:latest
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: homelab
    volumes:
      - "{{ data_dir }}/vaultwarden:/data"
    env:
      DOMAIN: "{{ VAULTWARDEN_DOMAIN }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.vw.rule: Host(`vw.fntz.net`)
      traefik.http.routers.vw.entrypoints: webSecure
      traefik.http.routers.vw.tls.certresolver: letsencrypt
      traefik.http.services.vw.loadbalancer.server.port: "80"
