ansible_user:
data_dir:
docker_network_name:
TZ:
PUID:
PGID:
ansible_become_pass:
media_path:

# api
API_CONTACT_WEBHOOK:
API_JWT_KEY:
API_STEAM_API_KEY:
API_LASTFM_API_KEY:
API_DATABASE_URL:
API_POSTGRES_PASSWORD:
API_ADMIN_KEY:

# plausible
PLAUSIBLE_BASE_URL:
PLAUSIBLE_SECRET_KEY_BASE:

# owncloud
OWNCLOUD_APP_URL:
OWNCLOUD_DB_PASSWORD:
OWNCLOUD_DB_USER:
OWNCLOUD_DB_DATABASE:
OWNCLOUD_DB_HOST:
OWNCLOUD_ADMIN_USERNAME:
OWNCLOUD_ADMIN_PASSWORD:

# traefik
TRAEFIK_DASH_URL:
TRAEFIK_CF_API_EMAIL:
TRAEFIK_CF_API_KEY:
TRAEFIK_HOST_IP:
TRAEFIK_VIDEO_MACHINE:
TRAEFIK_ENABLE_DASH:

# fivem
FIVEM_LICENSE_KEY:

# mastodon
MASTODON_DB_PASS:
MASTODON_LOCAL_DOMAIN:
MASTODON_SECRET_KEY_BASE:
MASTODON_OTP_SECRET:
MASTODON_VAPID_PRIVATE_KEY:
MASTODON_VAPID_PUBLIC_KEY:
MASTODON_ARE_DETERMINISTIC:
MASTODON_ARE_KEY_DERIVATION:
MASTODON_ARE_PRIMARY:

# wings
WINGS_URL:
WINGS_CONTAINER_DIR:

# glance
GLANCE_PIHOLE_TOKEN:
GLANCE_VIDEO_MACHINE:
GLANCE_JELLYFIN_URL:
GLANCE_JELLYFIN_TOKEN:

# tinyauth
TINYAUTH_USERS:
TINYAUTH_SECRET:
TINYAUTH_APP_URL:
TINYAUTH_GENERIC_CLIENT_ID:
TINYAUTH_GENERIC_CLIENT_SECRET:
TINYAUTH_GENERIC_AUTH_URL:
TINYAUTH_GENERIC_TOKEN_URL:
TINYAUTH_GENERIC_USER_URL:
TINYAUTH_GENERIC_SCOPES:
TINYAUTH_GENERIC_NAME:
TINYAUTH_REDIRECT_URL:
TINYAUTH_OAUTH_WHITELIST:
TINYAUTH_APP_TITLE:
TINYAUTH_BACKGROUND_IMAGE:

# code-server
CODE_PROXY_DOMAIN:
CODE_DEFAULT_WORKSPACE:

# dozzle
DOZZLE_ACTIONS:
DOZZLE_SHELL:

# gluetun
GLUETUN_VPN_SERVICE_PROVIDER:
GLUETUN_VPN_TYPE:
GLUETUN_WIREGUARD_PRIVATE_KEY:
GLUETUN_WIREGUARD_ADDRESSES:
GLUETUN_SERVER_COUNTRIES:
GLUETUN_SERVER_CITIES:
GLUETUN_SERVER_HOSTNAMES:

# immich
IMMICH_UPLOAD_LOCATION:
IMMICH_DB_DATA_LOCATION:
IMMICH_VERSION:
IMMICH_DB_PASSWORD:
IMMICH_DB_USERNAME:
IMMICH_DB_DATABASE_NAME:

# jellyfin
JELLYFIN_TV_PATH:
JELLYFIN_MOVIE_PATH:
JELLYFIN_MUSIC_PATH:

# navidrome
NAVIDROME_MUSIC_PATH:

# ntfy
NTFY_UPSTREAM_BASE_URL:
NTFY_BASE_URL:

# nzbget
NZBGET_USER:
NZBGET_PASS:
NZBGET_DOWNLOADS_PATH:

# pihole
PIHOLE_FTLCONF_WEBSERVER_API_PASSWORD:

# pocketid
POCKETID_APP_URL:
POCKETID_TRUST_PROXY:

# romm
ROMM_AUTH_SECRET_KEY:
ROMM_LIBRARY_PATH:
ROMM_IGDB_CLIENT_ID:
ROMM_IGDB_CLIENT_SECRET:
ROMM_OIDC_ENABLED:
ROMM_OIDC_PROVIDER:
ROMM_OIDC_CLIENT_ID:
ROMM_OIDC_CLIENT_SECRET:
ROMM_OIDC_REDIRECT_URL:
ROMM_SERVER_APPLICATION_URL:

# servarr
SERVARR_MEDIA_PATH:

# vaultwarden
VAULTWARDEN_DOMAIN:

# gitea runner
GITEA_INSTANCE_URL:
GITEA_RUNNER_REGISTRATION_TOKEN:
GITEA_RUNNER_NAME:
GITEA_RUNNER_LABELS:

# monitoring
GRAFANA_AUTH_ANONYMOUS_ENABLED:

# drop
DROP_GIANT_BOMB_API_KEY:

# obsidian
COUCHDB_USER:
COUCHDB_PASSWORD:

# helium
HELIUM_BASE_URL:
HELIUM_EXT_HMAC_SECRET:

# pterodactyl
PTERODACTYL_APP_URL:
PTERODACTYL_MYSQL_PASSWORD:
PTERODACTYL_MYSQL_ROOT_PASSWORD:

# frigate
FRIGATE_RECORDINGS_PATH:

# plex
PLEX_CLAIM_TOKEN:
